CREATE TABLE IF NOT EXISTS registration_form (
 id SERIAL PRIMARY KEY,
 nama VARCHAR(50) NOT NULL,
 nim DOUBLE PRECISION NOT NULL,
 email VARCHAR(50) NOT NULL,
 jurusan VARCHAR(50) NOT NULL,
 fakultas VARCHAR(50) NOT NULL,
 angkatan VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS student_data (
 id SERIAL PRIMARY KEY,
 nama VARCHAR(50) NOT NULL,
 nim DOUBLE PRECISION NOT NULL
);